CREATE SEQUENCE CLIENT_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE ASSURANCE_SEQUENCE START WITH 20 INCREMENT BY 1;

CREATE TABLE COMPTE_BANCAIRE(
	iban varchar(40) ,
	bic varchar(20) ,
        pCode varchar(20) ,
        mainAccount boolean ,
	PRIMARY KEY (iban)
);


CREATE TABLE CLIENT(
	idClient INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1) ,
	PRIMARY KEY (idClient)
);


CREATE TABLE COMPTE_CLIENT(
  idClient INTEGER ,
  iban varchar(40) ,
  PRIMARY KEY (idClient, iban) ,
	FOREIGN KEY (idClient) REFERENCES CLIENT(idClient) ,
  FOREIGN KEY (iban) REFERENCES COMPTE_BANCAIRE(iban)
);

CREATE TABLE CONTACT(
  idContact INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1) ,
  contactType varchar(20) ,
  val varchar(200) ,
  PRIMARY KEY (idContact)
);

CREATE TABLE CONTACT_CLIENT(
  idClient INTEGER ,
  idContact INTEGER ,
  PRIMARY KEY (idClient, idContact) ,
	FOREIGN KEY (idClient) REFERENCES CLIENT(idClient) ,
  FOREIGN KEY (idContact) REFERENCES CONTACT(idContact)
);


CREATE TABLE ASSURANCE(
    idAssurance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1) ,
    typeAssurance VARCHAR(10) ,
    subscriptionDate DATE ,
    birthDate DATE ,
    daftDate DATE ,
    PRIMARY KEY (idAssurance)
);

CREATE TABLE ASSURANCE_AUTO(
    idAssurance INTEGER ,
    immatriculation VARCHAR(30) ,
    bonnusMalus DOUBLE ,
    PRIMARY KEY (idAssurance)
);

CREATE TABLE ASSURANCE_HABITAT(
    idAssurance INTEGER ,
    address VARCHAR(400) ,
    coverValue int ,
    PRIMARY KEY (idAssurance)
);

CREATE TABLE CLIENT_ASSURANCE(
  idClient INTEGER ,
  idAssurance INTEGER ,
  PRIMARY KEY (idClient, idAssurance) ,
  FOREIGN KEY (idClient) REFERENCES CLIENT(idClient) ,
  FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
);

CREATE TABLE ECHEANCES(
  idEcheance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1) ,
  idAssurance INTEGER ,
  price INTEGER ,
  issueDate DATE ,
  paiementDate DATE ,
  issueBillDate DATE ,
  PRIMARY KEY (idEcheance) ,
  FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
);

CREATE TABLE PERSONNE_PHYSIQUE(
	idClient INTEGER,
        firstName VARCHAR(30) ,
	lastName VARCHAR(30) ,
        birthDate DATE ,
	PRIMARY KEY (idClient) ,
        FOREIGN KEY (idClient) REFERENCES CLIENT(idClient)
);

CREATE TABLE PERSONNE_MORALE(
	idClient INTEGER ,
        siren VARCHAR(30) ,
	companyName VARCHAR(30) ,
	PRIMARY KEY (idClient) ,
        FOREIGN KEY (idClient) REFERENCES CLIENT(idClient)
);

CREATE TABLE SINISTRE(
        idSinistre INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
        idAssurance INTEGER ,
        titre VARCHAR(100) ,
        description VARCHAR(500) ,
        sinistreDate DATE ,
        PRIMARY KEY (idSinistre) ,
        FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
);

CREATE TABLE SINISTRE_PHOTO(
    idSinistrePhoto INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1) ,
    idAssurance INTEGER ,
    nom VARCHAR(100) , 
    descriprion VARCHAR(100) ,
    date DATE ,
    PRIMARY KEY (idSinistrePhoto) ,
    FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
)
